### ISSUE TITLE
md5sum and control structure for gunzip addition

### ISSUE THREAD

**Issue by NoeRzPz** [NoeRzPz/testsim#1]
Hola Tomás, 
Quise mejorar run_pipeline.sh haciendo que chequeara la md5sum del genoma de ecoli descargado, pero no estoy segura de si el código añadido es correcto.
También añadí una estructura de control en el paso de descomprimido, para que si existe el archivo fasta descomprimido no haga nada y si no existe, lo descomprima, eso comprobé que funcionaba, pero supongo que sería mejor sustituir el nombre del archivo por una expresión que generalizase más el script, no? Ahí estoy un poco perdida de como hacerlo. Muchas gracias.
Saludos, 
Noelia

**Comment by tdido** [comment]
Una generalización razonable en este caso sería poner una variable con la URL del genoma arriba de todo. Luego podrías ver de llenar esa variable desde un archivo de configuración o algo por el estilo. Para este tipo de cosas yo prefier no usar argumentos ($1, $2...) porque considero mejor no meter inteligencia en las lineas de ejecución principales.

Respecto al md5sum, usando un truco que no vimos en las clases que se llama "process substitution", que permite usar un comando como si fuera un archivo  e.g. `<(echo hello)`, se puede hacer al vuelo.

```bash
GENOME_URL=ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/005/845/GCF_000005845.2_ASM584v2/GCF_000005845.2_ASM584v2_genomic.fna.gz
MD5_URL=ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/005/845/GCF_000005845.2_ASM584v2/md5checksums.txt
GENOME_FNAME=ecoli.fasta.gz

wget -O $GENOME_FNAME $GENOME_URL

#Computing md5sum
md5sum -c <(echo $(curl $MD5_URL | grep v2.genomic.fna | cut -d" " -f1) $GENOME_FNAME)
if [ "$?" -ne 0 ] 
then
    echo "md5sum check for downloaded file failed. Aborting."
    exit 1
fi
echo
```

**Comment by NoeRzPz** [comment]
Al principio me descargué  el archivo checksums, cambié el nombre de v2.genomic.fna para que fuera igual al que le dimos, pero no caí en el grep! Busqué una solución más sencilla y la cagué, jo qué rabia. Encima con el <() se puede resumir todo en una línea. Muchas gracias Tomás!!
